[package]
name = "year_2022"
version = "0.1.0"
edition = "2021"

include = ["day_01/input/calories.txt"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.0"